package neon.nsp.data.plugins.secgen;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.*;
import com.fs.starfarer.api.impl.campaign.ids.Conditions;
import com.fs.starfarer.api.impl.campaign.ids.Tags;
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceAbyssPluginImpl;
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceTerrainPlugin;
import com.fs.starfarer.api.impl.campaign.terrain.StarCoronaTerrainPlugin;
import org.lwjgl.util.vector.Vector2f;

import java.awt.*;

public class NSPInvictaSystemGen implements SectorGeneratorPlugin {

    public static String INVICTA_PLANET_ID = "test_planet_invicta";
    @Override
    public void generate(SectorAPI sector) {

        Vector2f location  = new Vector2f(-80000f, -32000f);
        // Dev runcode
//       runcode Global.getSector().getPlayerFleet().setLocation(-80000f, -32000f);

        StarSystemAPI system = Global.getSector().createStarSystem("Mourn"); // Name needs changing
        system.setName("Mourn"); // Name needs changing
        system.getLocation().set(location);
        system.addTag(Tags.THEME_HIDDEN);
        system.addTag(Tags.THEME_SPECIAL);
        system.addTag(Tags.SYSTEM_ABYSSAL);
        system.addTag(Tags.THEME_DERELICT);
        system.addTag(Tags.THEME_DERELICT_MOTHERSHIP);
        system.addTag(Tags.THEME_DERELICT_CRYOSLEEPER);
        system.addTag(Tags.NOT_RANDOM_MISSION_TARGET);
        system.addTag(Tags.DO_NOT_RESPAWN_PLAYER_IN);
        system.setLightColor(new Color(230, 207,190));

        system.setBackgroundTextureFilename("graphics/backgrounds/background5.jpg"); // Needs changing


        //Vigil Star
        SectorEntityToken systemCenter = system.initStar("invicta_star", // unique id for this star
                "star_white", // id in planets.json
                500f, 		  // radius (in pixels at default zoom)
                300, // corona
                10f, // solar wind burn level
                0.7f, // flare probability
                1.0f); // CR loss multiplier, good values are in the range of 1-5
//        SectorEntityToken systemCenter = system.initNonStarCenter();
        system.generateAnchorIfNeeded();



        PlanetAPI test2 = system.addPlanet("test_planet2", systemCenter, "test2", "ice_giant", 50, 300, 6000, 390);
//        hades.setCustomDescriptionId("tll_hades");
        test2.getMarket().addCondition(Conditions.VOLATILES_TRACE);
        test2.getMarket().addCondition(Conditions.EXTREME_WEATHER);
        test2.getMarket().addCondition(Conditions.HIGH_GRAVITY);
        test2.getMemoryWithoutUpdate().set("$test_planet2", true);

        PlanetAPI test = system.addPlanet(INVICTA_PLANET_ID, test2, "test", "tundra", 50, 50, 500, 273);
//        hades.setCustomDescriptionId("tll_hades");
        test.getMarket().addCondition(Conditions.VERY_COLD);
        test.getMarket().addCondition(Conditions.HIGH_GRAVITY);
        test.getMarket().addCondition(Conditions.RUINS_VAST);
        test.getMarket().addCondition(Conditions.MILD_CLIMATE);
        test.getMemoryWithoutUpdate().set("$test_planet", true);


        system.autogenerateHyperspaceJumpPoints(false,false,false);
        setAbyssalDetectedRanges(system);
    }

    public static void setAbyssalDetectedRanges(StarSystemAPI system) {
        if (system.getAutogeneratedJumpPointsInHyper() != null) {
            for (JumpPointAPI jp : system.getAutogeneratedJumpPointsInHyper()) {
                if (jp.isStarAnchor()) {
                    jp.addTag(Tags.STAR_HIDDEN_ON_MAP);
                }
                float range = HyperspaceAbyssPluginImpl.JUMP_POINT_DETECTED_RANGE;
                if (jp.isGasGiantAnchor()) {
                    range = HyperspaceAbyssPluginImpl.GAS_GIANT_DETECTED_RANGE;
                } else if (jp.isStarAnchor()) {
                    range = HyperspaceAbyssPluginImpl.STAR_DETECTED_RANGE;
                }

                setAbyssalDetectedRange(jp, range);
            }
        }

        if (system.getAutogeneratedNascentWellsInHyper() != null) {
            for (NascentGravityWellAPI well : system.getAutogeneratedNascentWellsInHyper()) {
                setAbyssalDetectedRange(well, HyperspaceAbyssPluginImpl.NASCENT_WELL_DETECTED_RANGE);
            }
        }
    }
    public static void setAbyssalDetectedRange(SectorEntityToken entity, float range) {
        float detectedRange = range / HyperspaceTerrainPlugin.ABYSS_SENSOR_RANGE_MULT;

        float maxSensorRange = Global.getSettings().getSensorRangeMaxHyper();
        float desired = detectedRange * HyperspaceTerrainPlugin.ABYSS_SENSOR_RANGE_MULT;
        if (desired > maxSensorRange) {
            entity.setExtendedDetectedAtRange(desired - maxSensorRange);
        }

        entity.setSensorProfile(1f);
        entity.setDiscoverable(false);
        entity.getDetectedRangeMod().modifyFlat("jpDetRange", detectedRange);

        float mult = Math.min(0.5f, 400f / range);
        entity.setDetectionRangeDetailsOverrideMult(mult);

        //getMemoryWithoutUpdate().set(MemFlags.EXTRA_SENSOR_INDICATORS, 3)
    }
}
